/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Cjuro
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        panTabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCanciones = new javax.swing.JTable();
        panRegistro = new javax.swing.JPanel();
        panControles1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtPaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPaterno1 = new javax.swing.JTextField();
        lblTituloPestaña1 = new javax.swing.JLabel();
        panTablaMantenimiento1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMantenimiento1 = new javax.swing.JTable();
        PanAmigos1 = new javax.swing.JPanel();
        btnAgregar2 = new javax.swing.JButton();
        btnEliminar2 = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        btnEditarNuevaVentana1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panMantenimiento = new javax.swing.JPanel();
        panControles = new javax.swing.JPanel();
        panControlesNorte = new javax.swing.JPanel();
        rbtnAudioCancion = new javax.swing.JRadioButton();
        rbtnAudioEpisodio = new javax.swing.JRadioButton();
        Nombre = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        panMantenimientoCard = new javax.swing.JPanel();
        panEpisodio = new javax.swing.JPanel();
        txtNombreAutor = new javax.swing.JTextField();
        Nombre2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPodcasts = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtDescripcionPodcasts = new javax.swing.JTextField();
        panCancion = new javax.swing.JPanel();
        cboGenero = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JLabel();
        txtNombreArtista = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNombreAlbum = new javax.swing.JTextField();
        panControlesSur = new javax.swing.JPanel();
        btnMostrar = new javax.swing.JButton();
        panTablaMantenimiento = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMantenimiento = new javax.swing.JTable();
        panMantenimiento1 = new javax.swing.JPanel();
        panControles3 = new javax.swing.JPanel();
        panControlesNorte1 = new javax.swing.JPanel();
        rbtnAudioCancion1 = new javax.swing.JRadioButton();
        rbtnAudioEpisodio1 = new javax.swing.JRadioButton();
        Nombre3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        panMantenimientoCard1 = new javax.swing.JPanel();
        panEpisodio1 = new javax.swing.JPanel();
        txtNombreAutor1 = new javax.swing.JTextField();
        Nombre4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtPodcasts1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtDescripcionPodcasts1 = new javax.swing.JTextField();
        panCancion1 = new javax.swing.JPanel();
        cboGenero1 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        Nombre5 = new javax.swing.JLabel();
        txtNombreArtista1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtNombreAlbum1 = new javax.swing.JTextField();
        panControlesSur1 = new javax.swing.JPanel();
        btnMostrar1 = new javax.swing.JButton();
        panTablaMantenimiento3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblMantenimiento3 = new javax.swing.JTable();
        panTabla1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCanciones1 = new javax.swing.JTable();
        PanBotones = new javax.swing.JPanel();
        btnProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTecnico = new javax.swing.JButton();
        btnVendedor = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panCentro = new javax.swing.JPanel();
        panRegistro1 = new javax.swing.JPanel();
        panControles2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        txtCantidadProducto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        lblTituloPestaña2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        panTablaInterna = new javax.swing.JPanel();
        panBotones = new javax.swing.JPanel();
        btnAgregarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnActualizarProducto = new javax.swing.JButton();
        btnCancelarProducto = new javax.swing.JButton();
        btnConsultarProducto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMantenimiento2 = new javax.swing.JTable();

        panPrincipal.setPreferredSize(new java.awt.Dimension(1394, 600));
        panPrincipal.setLayout(new java.awt.CardLayout());

        panTabla.setBackground(new java.awt.Color(0, 0, 0));
        panTabla.setPreferredSize(new java.awt.Dimension(1405, 1500));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblCanciones.setAutoCreateRowSorter(true);
        tblCanciones.setBackground(new java.awt.Color(0, 0, 0));
        tblCanciones.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        tblCanciones.setForeground(new java.awt.Color(204, 204, 204));
        tblCanciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblCanciones.setFillsViewportHeight(true);
        tblCanciones.setRowHeight(30);
        tblCanciones.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tblCanciones.setSelectionForeground(new java.awt.Color(204, 204, 204));
        tblCanciones.setShowHorizontalLines(false);
        tblCanciones.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tblCanciones);

        javax.swing.GroupLayout panTablaLayout = new javax.swing.GroupLayout(panTabla);
        panTabla.setLayout(panTablaLayout);
        panTablaLayout.setHorizontalGroup(
            panTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(425, Short.MAX_VALUE))
        );
        panTablaLayout.setVerticalGroup(
            panTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panPrincipal.add(panTabla, "tabla");

        panRegistro.setBackground(new java.awt.Color(0, 0, 0));
        panRegistro.setPreferredSize(new java.awt.Dimension(1396, 1500));
        panRegistro.setLayout(new java.awt.BorderLayout());

        panControles1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Nombre");

        txtPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaternoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Cantidad");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Precio");

        txtPaterno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaterno1ActionPerformed(evt);
            }
        });

        lblTituloPestaña1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        lblTituloPestaña1.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPestaña1.setText("Registro Producto");

        javax.swing.GroupLayout panControles1Layout = new javax.swing.GroupLayout(panControles1);
        panControles1.setLayout(panControles1Layout);
        panControles1Layout.setHorizontalGroup(
            panControles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panControles1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(panControles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panControles1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panControles1Layout.createSequentialGroup()
                        .addGroup(panControles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(panControles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNombres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(txtPaterno1, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(81, 81, 81))
            .addGroup(panControles1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPestaña1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panControles1Layout.setVerticalGroup(
            panControles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panControles1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTituloPestaña1)
                .addGap(27, 27, 27)
                .addGroup(panControles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(panControles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPaterno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(panControles1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panRegistro.add(panControles1, java.awt.BorderLayout.WEST);

        panTablaMantenimiento1.setBackground(new java.awt.Color(0, 0, 0));

        tblMantenimiento1.setAutoCreateRowSorter(true);
        tblMantenimiento1.setBackground(new java.awt.Color(46, 46, 46));
        tblMantenimiento1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        tblMantenimiento1.setForeground(new java.awt.Color(255, 255, 255));
        tblMantenimiento1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMantenimiento1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblMantenimiento1.setFillsViewportHeight(true);
        tblMantenimiento1.setRowHeight(30);
        tblMantenimiento1.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tblMantenimiento1.setSelectionForeground(new java.awt.Color(204, 204, 204));
        tblMantenimiento1.setShowHorizontalLines(false);
        jScrollPane4.setViewportView(tblMantenimiento1);

        javax.swing.GroupLayout panTablaMantenimiento1Layout = new javax.swing.GroupLayout(panTablaMantenimiento1);
        panTablaMantenimiento1.setLayout(panTablaMantenimiento1Layout);
        panTablaMantenimiento1Layout.setHorizontalGroup(
            panTablaMantenimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTablaMantenimiento1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1064, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );
        panTablaMantenimiento1Layout.setVerticalGroup(
            panTablaMantenimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTablaMantenimiento1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panRegistro.add(panTablaMantenimiento1, java.awt.BorderLayout.SOUTH);

        PanAmigos1.setBackground(new java.awt.Color(0, 0, 0));
        PanAmigos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        PanAmigos1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnAgregar2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnAgregar2.setText("Agregar");

        btnEliminar2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnEliminar2.setText("Eliminar");

        btnEditar1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnEditar1.setText("Actualizar");
        btnEditar1.setToolTipText("");

        btnCancelar1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnCancelar1.setText("Cancelar");
        btnCancelar1.setToolTipText("");

        btnEditarNuevaVentana1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnEditarNuevaVentana1.setText("Consultar");

        javax.swing.GroupLayout PanAmigos1Layout = new javax.swing.GroupLayout(PanAmigos1);
        PanAmigos1.setLayout(PanAmigos1Layout);
        PanAmigos1Layout.setHorizontalGroup(
            PanAmigos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanAmigos1Layout.createSequentialGroup()
                .addGroup(PanAmigos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanAmigos1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnCancelar1))
                    .addGroup(PanAmigos1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(PanAmigos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanAmigos1Layout.createSequentialGroup()
                                .addComponent(btnAgregar2)
                                .addGap(51, 51, 51)
                                .addComponent(btnEliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanAmigos1Layout.createSequentialGroup()
                                .addComponent(btnEditar1)
                                .addGap(35, 35, 35)
                                .addComponent(btnEditarNuevaVentana1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(228, 574, Short.MAX_VALUE))
        );
        PanAmigos1Layout.setVerticalGroup(
            PanAmigos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanAmigos1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PanAmigos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar2)
                    .addComponent(btnEliminar2))
                .addGap(56, 56, 56)
                .addGroup(PanAmigos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarNuevaVentana1)
                    .addComponent(btnEditar1))
                .addGap(51, 51, 51)
                .addComponent(btnCancelar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panRegistro.add(PanAmigos1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1394, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        panRegistro.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panPrincipal.add(panRegistro, "imagenes");

        panMantenimiento.setPreferredSize(new java.awt.Dimension(1398, 1500));
        panMantenimiento.setLayout(new java.awt.BorderLayout());

        panControles.setBackground(new java.awt.Color(0, 0, 0));
        panControles.setLayout(new java.awt.BorderLayout());

        panControlesNorte.setBackground(new java.awt.Color(0, 0, 0));

        rbtnAudioCancion.setBackground(new java.awt.Color(0, 0, 0));
        rbtnAudioCancion.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        rbtnAudioCancion.setForeground(new java.awt.Color(204, 204, 204));
        rbtnAudioCancion.setText("<Nombre>");

        rbtnAudioEpisodio.setBackground(new java.awt.Color(0, 0, 0));
        rbtnAudioEpisodio.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        rbtnAudioEpisodio.setForeground(new java.awt.Color(204, 204, 204));
        rbtnAudioEpisodio.setText("<Nombre>");

        Nombre.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        Nombre.setForeground(new java.awt.Color(204, 204, 204));
        Nombre.setText("Nombre:");

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("<Nombre>");

        javax.swing.GroupLayout panControlesNorteLayout = new javax.swing.GroupLayout(panControlesNorte);
        panControlesNorte.setLayout(panControlesNorteLayout);
        panControlesNorteLayout.setHorizontalGroup(
            panControlesNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panControlesNorteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panControlesNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panControlesNorteLayout.createSequentialGroup()
                        .addComponent(Nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panControlesNorteLayout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addComponent(rbtnAudioCancion)
                        .addGap(29, 29, 29)
                        .addComponent(rbtnAudioEpisodio)
                        .addGap(25, 25, 25))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panControlesNorteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(96, 96, 96))
        );
        panControlesNorteLayout.setVerticalGroup(
            panControlesNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panControlesNorteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panControlesNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnAudioEpisodio)
                    .addComponent(rbtnAudioCancion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panControlesNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        panControles.add(panControlesNorte, java.awt.BorderLayout.PAGE_START);

        panMantenimientoCard.setLayout(new java.awt.CardLayout());

        panEpisodio.setBackground(new java.awt.Color(0, 0, 0));

        Nombre2.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        Nombre2.setForeground(new java.awt.Color(204, 204, 204));
        Nombre2.setText("<Nombre>");

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("<Nombre>");

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Descripcion:");

        javax.swing.GroupLayout panEpisodioLayout = new javax.swing.GroupLayout(panEpisodio);
        panEpisodio.setLayout(panEpisodioLayout);
        panEpisodioLayout.setHorizontalGroup(
            panEpisodioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEpisodioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panEpisodioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcionPodcasts)
                    .addGroup(panEpisodioLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 197, Short.MAX_VALUE))
                    .addGroup(panEpisodioLayout.createSequentialGroup()
                        .addGroup(panEpisodioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre2)
                            .addComponent(jLabel15))
                        .addGap(27, 27, 27)
                        .addGroup(panEpisodioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPodcasts)
                            .addComponent(txtNombreAutor))))
                .addContainerGap())
        );
        panEpisodioLayout.setVerticalGroup(
            panEpisodioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEpisodioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panEpisodioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre2)
                    .addComponent(txtNombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panEpisodioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtPodcasts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcionPodcasts, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );

        panMantenimientoCard.add(panEpisodio, "episodio");

        panCancion.setBackground(new java.awt.Color(0, 0, 0));

        cboGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGeneroActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Genero:");

        Nombre1.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        Nombre1.setForeground(new java.awt.Color(204, 204, 204));
        Nombre1.setText("Artista:");

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Album:");

        javax.swing.GroupLayout panCancionLayout = new javax.swing.GroupLayout(panCancion);
        panCancion.setLayout(panCancionLayout);
        panCancionLayout.setHorizontalGroup(
            panCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCancionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCancionLayout.createSequentialGroup()
                        .addComponent(Nombre1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCancionLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panCancionLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(cboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panCancionLayout.setVerticalGroup(
            panCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCancionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre1))
                .addGap(31, 31, 31)
                .addGroup(panCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtNombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        panMantenimientoCard.add(panCancion, "cancion");

        panControles.add(panMantenimientoCard, java.awt.BorderLayout.CENTER);

        panControlesSur.setBackground(new java.awt.Color(0, 0, 0));

        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnImprimir.png"))); // NOI18N
        btnMostrar.setBorder(null);
        btnMostrar.setContentAreaFilled(false);
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panControlesSurLayout = new javax.swing.GroupLayout(panControlesSur);
        panControlesSur.setLayout(panControlesSurLayout);
        panControlesSurLayout.setHorizontalGroup(
            panControlesSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panControlesSurLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(btnMostrar)
                .addGap(52, 52, 52))
        );
        panControlesSurLayout.setVerticalGroup(
            panControlesSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panControlesSurLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnMostrar)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        panControles.add(panControlesSur, java.awt.BorderLayout.PAGE_END);

        panMantenimiento.add(panControles, java.awt.BorderLayout.LINE_START);

        panTablaMantenimiento.setBackground(new java.awt.Color(0, 0, 0));

        tblMantenimiento.setAutoCreateRowSorter(true);
        tblMantenimiento.setBackground(new java.awt.Color(46, 46, 46));
        tblMantenimiento.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        tblMantenimiento.setForeground(new java.awt.Color(255, 255, 255));
        tblMantenimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMantenimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblMantenimiento.setFillsViewportHeight(true);
        tblMantenimiento.setRowHeight(30);
        tblMantenimiento.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tblMantenimiento.setSelectionForeground(new java.awt.Color(204, 204, 204));
        tblMantenimiento.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(tblMantenimiento);

        javax.swing.GroupLayout panTablaMantenimientoLayout = new javax.swing.GroupLayout(panTablaMantenimiento);
        panTablaMantenimiento.setLayout(panTablaMantenimientoLayout);
        panTablaMantenimientoLayout.setHorizontalGroup(
            panTablaMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTablaMantenimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panTablaMantenimientoLayout.setVerticalGroup(
            panTablaMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTablaMantenimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panMantenimiento.add(panTablaMantenimiento, java.awt.BorderLayout.CENTER);

        panPrincipal.add(panMantenimiento, "mantenimiento");

        panMantenimiento1.setPreferredSize(new java.awt.Dimension(1398, 1500));
        panMantenimiento1.setLayout(new java.awt.BorderLayout());

        panControles3.setBackground(new java.awt.Color(0, 0, 0));
        panControles3.setLayout(new java.awt.BorderLayout());

        panControlesNorte1.setBackground(new java.awt.Color(0, 0, 0));

        rbtnAudioCancion1.setBackground(new java.awt.Color(0, 0, 0));
        rbtnAudioCancion1.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        rbtnAudioCancion1.setForeground(new java.awt.Color(204, 204, 204));
        rbtnAudioCancion1.setText("<Nombre>");

        rbtnAudioEpisodio1.setBackground(new java.awt.Color(0, 0, 0));
        rbtnAudioEpisodio1.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        rbtnAudioEpisodio1.setForeground(new java.awt.Color(204, 204, 204));
        rbtnAudioEpisodio1.setText("<Nombre>");

        Nombre3.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        Nombre3.setForeground(new java.awt.Color(204, 204, 204));
        Nombre3.setText("Nombre:");

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("<Nombre>");

        javax.swing.GroupLayout panControlesNorte1Layout = new javax.swing.GroupLayout(panControlesNorte1);
        panControlesNorte1.setLayout(panControlesNorte1Layout);
        panControlesNorte1Layout.setHorizontalGroup(
            panControlesNorte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panControlesNorte1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panControlesNorte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panControlesNorte1Layout.createSequentialGroup()
                        .addComponent(Nombre3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panControlesNorte1Layout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addComponent(rbtnAudioCancion1)
                        .addGap(29, 29, 29)
                        .addComponent(rbtnAudioEpisodio1)
                        .addGap(25, 25, 25))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panControlesNorte1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(96, 96, 96))
        );
        panControlesNorte1Layout.setVerticalGroup(
            panControlesNorte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panControlesNorte1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panControlesNorte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnAudioEpisodio1)
                    .addComponent(rbtnAudioCancion1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panControlesNorte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre3)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        panControles3.add(panControlesNorte1, java.awt.BorderLayout.PAGE_START);

        panMantenimientoCard1.setLayout(new java.awt.CardLayout());

        panEpisodio1.setBackground(new java.awt.Color(0, 0, 0));

        Nombre4.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        Nombre4.setForeground(new java.awt.Color(204, 204, 204));
        Nombre4.setText("<Nombre>");

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("<Nombre>");

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Descripcion:");

        javax.swing.GroupLayout panEpisodio1Layout = new javax.swing.GroupLayout(panEpisodio1);
        panEpisodio1.setLayout(panEpisodio1Layout);
        panEpisodio1Layout.setHorizontalGroup(
            panEpisodio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEpisodio1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panEpisodio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcionPodcasts1)
                    .addGroup(panEpisodio1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 197, Short.MAX_VALUE))
                    .addGroup(panEpisodio1Layout.createSequentialGroup()
                        .addGroup(panEpisodio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre4)
                            .addComponent(jLabel19))
                        .addGap(27, 27, 27)
                        .addGroup(panEpisodio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPodcasts1)
                            .addComponent(txtNombreAutor1))))
                .addContainerGap())
        );
        panEpisodio1Layout.setVerticalGroup(
            panEpisodio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEpisodio1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panEpisodio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre4)
                    .addComponent(txtNombreAutor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panEpisodio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtPodcasts1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcionPodcasts1, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE)
                .addContainerGap())
        );

        panMantenimientoCard1.add(panEpisodio1, "episodio");

        panCancion1.setBackground(new java.awt.Color(0, 0, 0));

        cboGenero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGenero1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Genero:");

        Nombre5.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        Nombre5.setForeground(new java.awt.Color(204, 204, 204));
        Nombre5.setText("Artista:");

        jLabel22.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Album:");

        javax.swing.GroupLayout panCancion1Layout = new javax.swing.GroupLayout(panCancion1);
        panCancion1.setLayout(panCancion1Layout);
        panCancion1Layout.setHorizontalGroup(
            panCancion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCancion1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCancion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCancion1Layout.createSequentialGroup()
                        .addComponent(Nombre5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombreArtista1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCancion1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombreAlbum1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panCancion1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(cboGenero1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panCancion1Layout.setVerticalGroup(
            panCancion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCancion1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCancion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreArtista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre5))
                .addGap(31, 31, 31)
                .addGroup(panCancion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtNombreAlbum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panCancion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cboGenero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(997, Short.MAX_VALUE))
        );

        panMantenimientoCard1.add(panCancion1, "cancion");

        panControles3.add(panMantenimientoCard1, java.awt.BorderLayout.CENTER);

        panControlesSur1.setBackground(new java.awt.Color(0, 0, 0));

        btnMostrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnImprimir.png"))); // NOI18N
        btnMostrar1.setBorder(null);
        btnMostrar1.setContentAreaFilled(false);
        btnMostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panControlesSur1Layout = new javax.swing.GroupLayout(panControlesSur1);
        panControlesSur1.setLayout(panControlesSur1Layout);
        panControlesSur1Layout.setHorizontalGroup(
            panControlesSur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panControlesSur1Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(btnMostrar1)
                .addGap(52, 52, 52))
        );
        panControlesSur1Layout.setVerticalGroup(
            panControlesSur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panControlesSur1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnMostrar1)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        panControles3.add(panControlesSur1, java.awt.BorderLayout.PAGE_END);

        panMantenimiento1.add(panControles3, java.awt.BorderLayout.LINE_START);

        panTablaMantenimiento3.setBackground(new java.awt.Color(0, 0, 0));

        tblMantenimiento3.setAutoCreateRowSorter(true);
        tblMantenimiento3.setBackground(new java.awt.Color(46, 46, 46));
        tblMantenimiento3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        tblMantenimiento3.setForeground(new java.awt.Color(255, 255, 255));
        tblMantenimiento3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMantenimiento3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblMantenimiento3.setFillsViewportHeight(true);
        tblMantenimiento3.setRowHeight(30);
        tblMantenimiento3.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tblMantenimiento3.setSelectionForeground(new java.awt.Color(204, 204, 204));
        tblMantenimiento3.setShowHorizontalLines(false);
        jScrollPane6.setViewportView(tblMantenimiento3);

        javax.swing.GroupLayout panTablaMantenimiento3Layout = new javax.swing.GroupLayout(panTablaMantenimiento3);
        panTablaMantenimiento3.setLayout(panTablaMantenimiento3Layout);
        panTablaMantenimiento3Layout.setHorizontalGroup(
            panTablaMantenimiento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTablaMantenimiento3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panTablaMantenimiento3Layout.setVerticalGroup(
            panTablaMantenimiento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTablaMantenimiento3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(740, Short.MAX_VALUE))
        );

        panMantenimiento1.add(panTablaMantenimiento3, java.awt.BorderLayout.CENTER);

        panTabla1.setBackground(new java.awt.Color(0, 0, 0));
        panTabla1.setPreferredSize(new java.awt.Dimension(1405, 1500));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblCanciones1.setAutoCreateRowSorter(true);
        tblCanciones1.setBackground(new java.awt.Color(0, 0, 0));
        tblCanciones1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        tblCanciones1.setForeground(new java.awt.Color(204, 204, 204));
        tblCanciones1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCanciones1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblCanciones1.setFillsViewportHeight(true);
        tblCanciones1.setRowHeight(30);
        tblCanciones1.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tblCanciones1.setSelectionForeground(new java.awt.Color(204, 204, 204));
        tblCanciones1.setShowHorizontalLines(false);
        tblCanciones1.setShowVerticalLines(false);
        jScrollPane3.setViewportView(tblCanciones1);

        javax.swing.GroupLayout panTabla1Layout = new javax.swing.GroupLayout(panTabla1);
        panTabla1.setLayout(panTabla1Layout);
        panTabla1Layout.setHorizontalGroup(
            panTabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTabla1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panTabla1Layout.setVerticalGroup(
            panTabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTabla1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanBotones.setBackground(new java.awt.Color(0, 0, 0));
        PanBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        btnProducto.setBackground(new java.awt.Color(0, 0, 0));
        btnProducto.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnProducto.setForeground(new java.awt.Color(204, 204, 204));
        btnProducto.setText("Productos");
        btnProducto.setBorder(null);
        btnProducto.setContentAreaFilled(false);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("MODULOS");

        btnTecnico.setBackground(new java.awt.Color(0, 0, 0));
        btnTecnico.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnTecnico.setForeground(new java.awt.Color(204, 204, 204));
        btnTecnico.setText("Tecnico");
        btnTecnico.setBorder(null);
        btnTecnico.setContentAreaFilled(false);

        btnVendedor.setBackground(new java.awt.Color(0, 0, 0));
        btnVendedor.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnVendedor.setForeground(new java.awt.Color(204, 204, 204));
        btnVendedor.setText("Vendedor");
        btnVendedor.setBorder(null);
        btnVendedor.setContentAreaFilled(false);

        btnSalir.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 204, 204));
        btnSalir.setText("X");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setContentAreaFilled(false);

        javax.swing.GroupLayout PanBotonesLayout = new javax.swing.GroupLayout(PanBotones);
        PanBotones.setLayout(PanBotonesLayout);
        PanBotonesLayout.setHorizontalGroup(
            PanBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanBotonesLayout.createSequentialGroup()
                .addGroup(PanBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanBotonesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnProducto)
                            .addComponent(btnTecnico)
                            .addComponent(btnVendedor)))
                    .addGroup(PanBotonesLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PanBotonesLayout.setVerticalGroup(
            PanBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(btnProducto)
                .addGap(134, 134, 134)
                .addComponent(btnTecnico)
                .addGap(30, 30, 30)
                .addComponent(btnVendedor)
                .addGap(66, 66, 66)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(527, Short.MAX_VALUE))
        );

        getContentPane().add(PanBotones, java.awt.BorderLayout.LINE_START);

        panCentro.setLayout(new java.awt.CardLayout());

        panRegistro1.setBackground(new java.awt.Color(0, 0, 0));
        panRegistro1.setPreferredSize(new java.awt.Dimension(1000, 900));

        panControles2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Nombre");

        txtCantidadProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadProductoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Cantidad");

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Precio");

        txtPrecioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioProductoActionPerformed(evt);
            }
        });

        lblTituloPestaña2.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        lblTituloPestaña2.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPestaña2.setText("Registro Producto");

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Codigo");

        txtCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panControles2Layout = new javax.swing.GroupLayout(panControles2);
        panControles2.setLayout(panControles2Layout);
        panControles2Layout.setHorizontalGroup(
            panControles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panControles2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(panControles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addGroup(panControles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTituloPestaña2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panControles2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addGroup(panControles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(137, 137, 137)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panControles2Layout.createSequentialGroup()
                        .addGroup(panControles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panControles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panControles2Layout.setVerticalGroup(
            panControles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panControles2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPestaña2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panControles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panControles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panControles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panControles2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(56, 56, 56))
        );

        panTablaInterna.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panTablaInternaLayout = new javax.swing.GroupLayout(panTablaInterna);
        panTablaInterna.setLayout(panTablaInternaLayout);
        panTablaInternaLayout.setHorizontalGroup(
            panTablaInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panTablaInternaLayout.setVerticalGroup(
            panTablaInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        panBotones.setBackground(new java.awt.Color(0, 0, 0));
        panBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        panBotones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnAgregarProducto.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnAgregarProducto.setText("Agregar");

        btnEliminarProducto.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnEliminarProducto.setText("Eliminar");

        btnActualizarProducto.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnActualizarProducto.setText("Actualizar");
        btnActualizarProducto.setToolTipText("");

        btnCancelarProducto.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnCancelarProducto.setText("Cancelar");
        btnCancelarProducto.setToolTipText("");

        btnConsultarProducto.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnConsultarProducto.setText("Consultar");

        javax.swing.GroupLayout panBotonesLayout = new javax.swing.GroupLayout(panBotones);
        panBotones.setLayout(panBotonesLayout);
        panBotonesLayout.setHorizontalGroup(
            panBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarProducto)
                .addGap(127, 127, 127))
            .addGroup(panBotonesLayout.createSequentialGroup()
                .addGroup(panBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBotonesLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnAgregarProducto))
                    .addGroup(panBotonesLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnConsultarProducto)))
                .addGap(43, 43, 43)
                .addGroup(panBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarProducto))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panBotonesLayout.setVerticalGroup(
            panBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProducto)
                    .addComponent(btnEliminarProducto))
                .addGap(51, 51, 51)
                .addGroup(panBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarProducto)
                    .addComponent(btnConsultarProducto))
                .addGap(37, 37, 37)
                .addComponent(btnCancelarProducto)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        tblMantenimiento2.setAutoCreateRowSorter(true);
        tblMantenimiento2.setBackground(new java.awt.Color(46, 46, 46));
        tblMantenimiento2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        tblMantenimiento2.setForeground(new java.awt.Color(255, 255, 255));
        tblMantenimiento2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMantenimiento2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblMantenimiento2.setFillsViewportHeight(true);
        tblMantenimiento2.setRowHeight(30);
        tblMantenimiento2.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tblMantenimiento2.setSelectionForeground(new java.awt.Color(204, 204, 204));
        tblMantenimiento2.setShowHorizontalLines(false);
        jScrollPane5.setViewportView(tblMantenimiento2);

        javax.swing.GroupLayout panRegistro1Layout = new javax.swing.GroupLayout(panRegistro1);
        panRegistro1.setLayout(panRegistro1Layout);
        panRegistro1Layout.setHorizontalGroup(
            panRegistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRegistro1Layout.createSequentialGroup()
                .addComponent(panControles2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panRegistro1Layout.createSequentialGroup()
                .addComponent(panTablaInterna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panRegistro1Layout.setVerticalGroup(
            panRegistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRegistro1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panRegistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panControles2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panRegistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panRegistro1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(panTablaInterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addGroup(panRegistro1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5)))
                .addContainerGap())
        );

        panCentro.add(panRegistro1, "panRegistro");

        getContentPane().add(panCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void cboGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboGeneroActionPerformed

    private void txtPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaternoActionPerformed

    private void txtPaterno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaterno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaterno1ActionPerformed

    private void txtCantidadProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadProductoActionPerformed

    private void txtPrecioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProductoActionPerformed

    private void cboGenero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGenero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboGenero1ActionPerformed

    private void btnMostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrar1ActionPerformed

    private void txtCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel Nombre3;
    private javax.swing.JLabel Nombre4;
    private javax.swing.JLabel Nombre5;
    private javax.swing.JPanel PanAmigos1;
    private javax.swing.JPanel PanBotones;
    public javax.swing.JButton btnActualizarProducto;
    public javax.swing.JButton btnAgregar2;
    public javax.swing.JButton btnAgregarProducto;
    public javax.swing.JButton btnCancelar1;
    public javax.swing.JButton btnCancelarProducto;
    public javax.swing.JButton btnConsultarProducto;
    public javax.swing.JButton btnEditar1;
    public javax.swing.JButton btnEditarNuevaVentana1;
    public javax.swing.JButton btnEliminar2;
    public javax.swing.JButton btnEliminarProducto;
    public javax.swing.JButton btnMostrar;
    public javax.swing.JButton btnMostrar1;
    public javax.swing.JButton btnProducto;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnTecnico;
    public javax.swing.JButton btnVendedor;
    public javax.swing.JComboBox<String> cboGenero;
    public javax.swing.JComboBox<String> cboGenero1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JLabel lblTituloPestaña1;
    public javax.swing.JLabel lblTituloPestaña2;
    private javax.swing.JPanel panBotones;
    private javax.swing.JPanel panCancion;
    private javax.swing.JPanel panCancion1;
    public javax.swing.JPanel panCentro;
    private javax.swing.JPanel panControles;
    private javax.swing.JPanel panControles1;
    private javax.swing.JPanel panControles2;
    private javax.swing.JPanel panControles3;
    private javax.swing.JPanel panControlesNorte;
    private javax.swing.JPanel panControlesNorte1;
    private javax.swing.JPanel panControlesSur;
    private javax.swing.JPanel panControlesSur1;
    private javax.swing.JPanel panEpisodio;
    private javax.swing.JPanel panEpisodio1;
    private javax.swing.JPanel panMantenimiento;
    private javax.swing.JPanel panMantenimiento1;
    public javax.swing.JPanel panMantenimientoCard;
    public javax.swing.JPanel panMantenimientoCard1;
    public javax.swing.JPanel panPrincipal;
    private javax.swing.JPanel panRegistro;
    private javax.swing.JPanel panRegistro1;
    private javax.swing.JPanel panTabla;
    private javax.swing.JPanel panTabla1;
    private javax.swing.JPanel panTablaInterna;
    private javax.swing.JPanel panTablaMantenimiento;
    private javax.swing.JPanel panTablaMantenimiento1;
    private javax.swing.JPanel panTablaMantenimiento3;
    public javax.swing.JRadioButton rbtnAudioCancion;
    public javax.swing.JRadioButton rbtnAudioCancion1;
    public javax.swing.JRadioButton rbtnAudioEpisodio;
    public javax.swing.JRadioButton rbtnAudioEpisodio1;
    public javax.swing.JTable tblCanciones;
    public javax.swing.JTable tblCanciones1;
    public javax.swing.JTable tblMantenimiento;
    public javax.swing.JTable tblMantenimiento1;
    public javax.swing.JTable tblMantenimiento2;
    public javax.swing.JTable tblMantenimiento3;
    public javax.swing.JTextField txtCantidadProducto;
    public javax.swing.JTextField txtCodigoProducto;
    public javax.swing.JTextField txtDescripcionPodcasts;
    public javax.swing.JTextField txtDescripcionPodcasts1;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNombre1;
    public javax.swing.JTextField txtNombreAlbum;
    public javax.swing.JTextField txtNombreAlbum1;
    public javax.swing.JTextField txtNombreArtista;
    public javax.swing.JTextField txtNombreArtista1;
    public javax.swing.JTextField txtNombreAutor;
    public javax.swing.JTextField txtNombreAutor1;
    public javax.swing.JTextField txtNombreProducto;
    public javax.swing.JTextField txtNombres;
    public javax.swing.JTextField txtPaterno;
    public javax.swing.JTextField txtPaterno1;
    public javax.swing.JTextField txtPodcasts;
    public javax.swing.JTextField txtPodcasts1;
    public javax.swing.JTextField txtPrecioProducto;
    // End of variables declaration//GEN-END:variables
}
